POST http://localhost:5000/api/data
content-type: application/json
Connection: keep-alive
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjIzNmVmMDZiMDBhN2IzZDI3ZGQ5N2M3In0sImlhdCI6MTY0Nzc2NzY4MCwiZXhwIjoxNjQ3ODAzNjgwfQ.2uwX6AYwcy0pmu9u_3s45lD9DNRPMONf_BAOaxDGbnM

{
    "start":"2022-03-19T00:00:00Z",
    "end":"2022-03-20T23:59:59Z",
    "name": "temp_sensor"
}